- name: Deploy Credo crcli to local BMC
  hosts: goodnow_bmcs
  gather_facts: false
  tasks:
    - name: Ensure /tmp/tools/ exists
      file:
        path: /tmp/tools/
        state: directory
        mode: '0755'

    - name: Copy crcli binary to local tools path
      copy:
        src: ../files/linux-x64/crcli
        dest: /tmp/tools/crcli
        mode: '0755'

    - name: Run crcli version check (mock command)
      command: /tmp/tools/crcli --version
      register: crcli_output
      ignore_errors: true

    - name: Print crcli output
      debug:
        var: crcli_output.stdout